#!/bin/bash
while true
do
	res=(`grep "khung bo\|bom" -rl .`)
	if [ "${#res[@]}" -gt 0 ];
	then
		ind=0
		while [ "$ind" -lt "${#res[@]}" ]; do
			echo "${res[ind]} -> `stat -c '%U' ${res[ind]}`" > mailing
			((ind++))
		done
	else
		echo "`date +%T`: an toan" > /tmp/sec
	fi
	sleep 60
done